export const repositories = [
    {
        name: 'University of Arkansas Community College',
        location: 'Batesville, AR',
        image: './img/uaccb-repository.png',
        years: '2',
        type: 'Public',
        size: 'Small',
        lms: 'Blackboard',
        link: 'https://uaccb.simplesyllabus.com/en-US/syllabus-library',
        description: 'UACC, a leading community college in Arkansas, has partnered with Simple Syllabus since August 2022 to streamline syllabus management and enhance academic efficiency.',
    },
    {
        name: 'The University of Texas at San Antonio',
        location: 'San Antonio, TX',
        image: './img/utsa-repository.png',
        years: '4',
        type: 'Public',
        size: 'Large',
        lms: 'Canvas',
        link: 'https://utsa.simplesyllabus.com/en-US/syllabus-library',
        description: 'UTSA, a leading public research university, has partnered with Simple Syllabus since July 2021, enhancing syllabus management and supporting academic excellence.',
    },
    {
        name: 'The University of Denver University College',
        location: 'Denver, CO',
        image: './img/du-repository.png',
        years: '4',
        type: 'Private',
        size: 'Large',
        lms: 'Canvas',
        link: 'https://du.simplesyllabus.com/en-US/syllabus-library',
        description: 'The University of Denver has partnered with Simple Syllabus since July 2020, enhancing syllabus management and supporting academic excellence.',
    },
    {
        name: 'South Suburban College',
        location: 'South Holland, IL',
        image: './img/ssc-repository.png',
        years: '2',
        type: 'Public',
        size: 'Medium',
        lms: 'Brightspace',
        link: 'https://ssc.simplesyllabus.com/en-US/syllabus-library',
        description: 'SSC, a prominent community college in Illinois, has partnered with Simple Syllabus since October 2022, enhancing syllabus management and supporting student success.',
    },
    {
        name: 'Alamo Colleges District',
        location: 'San Antonio, TX',
        image: './img/alamo-repository.png',
        years: '2',
        type: 'Public',
        size: 'Large',
        lms: 'Canvas',
        link: 'https://alamo.simplesyllabus.com/en-US/syllabus-library',
        description: 'Alamo Colleges District, a network of five Texas community colleges, partnered with Simple Syllabus in November 2021 to enhance syllabus management and support student success.',
    },
    {
        name: 'University of California Santa Cruz Extension',
        location: 'Santa Cruz, CA',
        image: './img/ucsc-repository.png',
        years: '4',
        type: 'Public',
        size: 'Large',
        lms: 'Canvas',
        link: 'https://ucsc-extension.simplesyllabus.com/en-US/syllabus-library',
        description: 'UC Santa Cruz Extension, renowned for professional development and continuing education, has partnered with Simple Syllabus since September 2021 to improve syllabi.',
    },
    {
        name: 'McMaster University',
        location: 'Hamilton, ON Canada',
        image: './img/mcmaster-repository.png',
        years: '4',
        type: 'Public',
        size: 'Large',
        lms: 'Brightspace',
        link: 'https://mcmaster.simplesyllabus.com/en-US/syllabus-library',
        description: 'McMaster University, a top Canadian research institution, has partnered with Simple Syllabus since October 2021 to streamline syllabus management.',
    },
    {
        name: 'Temple College',
        location: 'Temple, TX',
        image: './img/templejc-repository.png',
        years: '2',
        type: 'Public',
        size: 'Medium',
        lms: 'Brightspace',
        link: 'https://templejc.simplesyllabus.com/en-US/syllabus-library',
        description: 'Temple College has partnered with Simple Syllabus since May 2023, streamlining syllabus management and enhancing educational efficiency.',
    },
    {
        name: 'University of Central Florida',
        location: 'Orlando, FL',
        image: './img/ucf-repository.png',
        years: '4',
        type: 'Public',
        size: 'Large',
        lms: 'Canvas',
        link: 'https://ucf.simplesyllabus.com/en-US/syllabus-library',
        description: 'The University of Central Florida, one of the largest universities in the U.S., partnered with Simple Syllabus in April 2023 to streamline syllabus management.',
    }, 
    {
        name: 'Iowa Community College Online Consortium',
        location: 'Iowa',
        image: './img/iccoc-repository.png',
        years: '2',
        type: 'Public',
        size: 'Medium',
        lms: 'Canvas',
        link: 'https://iccoc.simplesyllabus.com/en-US/syllabus-library',
        description: 'ICCOC, serving multiple community colleges in Iowa, partnered with Simple Syllabus in July 2020 to further support high-quality online education through quality syllabi.',
    },
    {
        name: 'Pellissippi State Community College',
        location: 'Knoxville, TN',
        image: './img/pstcc-repository.png',
        years: '2',
        type: 'Public',
        size: 'Medium',
        lms: 'Brightspace',
        link: 'https://pstcc.simplesyllabus.com/en-US/syllabus-library',
        description: 'PSCC, a leading institution in Tennessee, partnered with Simple Syllabus in 2023 to enhance syllabus consistency, simplify updates, and improve faculty collaboration.',
    },
    {
        name: 'St. Charles Community College',
        location: 'Cottleville, MO',
        image: './img/stchas-repository.png',
        years: '2',
        type: 'Public',
        size: 'Medium',
        lms: 'Canvas',
        link: 'https://stchas.simplesyllabus.com/en-US/syllabus-library',
        description: 'St. Charles Community College, a prominent Missouri institution, partnered with Simple Syllabus in 2023 to streamline syllabus creation and ensure accreditation compliance.',
    },
    {
        name: 'Everett Community College',
        location: 'Everett, WA',
        image: './img/everettcc-repository.png',
        years: '2',
        type: 'Public',
        size: 'Medium',
        lms: 'Canvas',
        link: 'https://everettcc.simplesyllabus.com/en-US/syllabus-library',
        description: 'Everett Community College partnered with Simple Syllabus in May 2023 to streamline syllabus management, improve compliance, and enhance the student learning experience.',
    },
    {
        name: 'Valencia College',
        location: 'Orlando, FL',
        image: './img/valenciacollege-repository.png',
        years: '4',
        type: 'Public',
        size: 'Large',
        lms: 'Canvas',
        link: 'https://valenciacollege.simplesyllabus.com/en-US/syllabus-library',
        description: 'Valencia College partnered with Simple Syllabus in 2022 to streamline syllabus creation, ensure accreditation compliance, and enhance the student learning experience.',
    },
    {
        name: 'Upper Iowa University',
        location: 'Fayette, Iowa',
        image: './img/uiu-repository.png',
        years: '4',
        type: 'Private',
        size: 'Medium',
        lms: 'Canvas',
        link: 'https://uiu.simplesyllabus.com/en-US/syllabus-library',
        description: 'UIU partnered with Simple Syllabus in 2021 to streamline syllabus management, ensure accreditation compliance, enhance faculty collaboration, and support student success.',
    },
    {
        name: 'University of Arkansas Hope-Texarkana',
        location: 'Hope, AR',
        image: './img/uaht-repository.png',
        years: '2',
        type: 'Public',
        size: 'Small',
        lms: 'Blackboard',
        link: 'https://uaht.simplesyllabus.com/en-US/syllabus-library',
        description: 'The University of Arkansas Hope-Texarkana partnered with Simple Syllabus in July 2022 to streamline syllabus management, ensure compliance, and enhance faculty collaboration.',
    },
    {
        name: 'SAE University College',
        location: 'Australia',
        image: './img/sae-au-repository.png',
        years: '4',
        type: 'Private',
        size: 'Medium',
        lms: 'Canvas',
        link: 'https://sae-au.simplesyllabus.com/en-US/syllabus-library',
        description: 'SAE University College, a global leader in creative media education, partnered with Simple Syllabus in 2021 to streamline syllabus management and improve the student experience.',
    },
    {
        name: 'Southwest Texas Junior College',
        location: 'Uvalde County, Texas',
        image: './img/swtjc-repository.png',
        years: '2',
        type: 'Public',
        size: 'Medium',
        lms: 'Canvas',
        link: 'https://swtjc.simplesyllabus.com/en-US/syllabus-library',
        description: 'Southwest Texas Junior College partnered with Simple Syllabus in 2021 to streamline syllabus management, ensure accreditation compliance, and improve the student experience.',
    },
]
